### ISSUE TITLE
exception in deserialization brought down application

### ISSUE THREAD

**Issue by anthony-cole** [TheCodeKing/XDMessaging.Net#10]
We are getting an unhandled exception through the XDMessaging code.

Our application has an unhandled exception handler in it which is logging out the error we caught but it seems the application is still brought down by XDMessaging.  

This particular case seems to be caused by some invalid Json, multiple items named channel or something.  I looked at the code and I think adding a SerializationException catch would solve this in
XDMessaging.Net / src / XDMessaging.Lite / Transport / IOStream / XDIoStreamListener.cs .

I'm going to get the code and give this a try instead of using the nugget

I think what is causing this is a writer shutting down in the middle of writing out a message

--------------------------

2017-01-27 17:06:18.7261 Default 5260-10-1 * An unhandled exception occured. : System.Runtime.Serialization.SerializationException: The data contract type 'XDMessaging.Messages.DataGram' cannot be deserialized because the data member 'channel' was found more than once in the input.

Server stack trace: 
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ThrowDuplicateMemberException(Object obj, XmlDictionaryString[] memberNames, Int32 memberIndex)
   at ReadDataGramFromJson(XmlReaderDelegator , XmlObjectSerializerReadContextComplexJson , XmlDictionaryString , XmlDictionaryString[] )
   at System.Runtime.Serialization.Json.JsonClassDataContract.ReadJsonValueCore(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.JsonDataContract.ReadJsonValue(XmlReaderDelegator jsonReader, XmlObjectSerializerReadContextComplexJson context)
   at System.Runtime.Serialization.Json.XmlObjectSerializerReadContextComplexJson.ReadDataContractValue(DataContract dataContract, XmlReaderDelegator reader)
   at System.Runtime.Serialization.XmlObjectSerializerReadContext.InternalDeserialize(XmlReaderDelegator reader, String name, String ns, Type declaredType, DataContract& dataContract)
   at System.Runtime.Serialization.XmlObjectSerializerReadContextComplex.InternalDeserialize(XmlReaderDelegator xmlReader, Type declaredType, DataContract dataContract, String name, String ns)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.InternalReadObject(XmlReaderDelegator xmlReader, Boolean verifyObjectName)
   at System.Runtime.Serialization.XmlObjectSerializer.InternalReadObject(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.XmlObjectSerializer.ReadObjectHandleExceptions(XmlReaderDelegator reader, Boolean verifyObjectName, DataContractResolver dataContractResolver)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(XmlDictionaryReader reader)
   at System.Runtime.Serialization.Json.DataContractJsonSerializer.ReadObject(Stream stream)
   at TheCodeKing.Utils.Serialization.JsonSerializer.Deserialize[T](String data)
   at XDMessaging.Specialized.SpecializedSerializer.Deserialize[T](String data)
   at XDMessaging.Transport.IOStream.XDIoStreamListener.ProcessMessage(String fullPath)
   at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)

Exception rethrown at [0]: 
   at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase)
   at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(Object NotUsed, MessageData& msgData)
   at System.Action`1.EndInvoke(IAsyncResult result)
   at System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage(IMessage msg)
   at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
   at System.Runtime.Remoting.Proxies.AgileAsyncWorkerItem.ThreadPoolCallBack(Object o)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by TheCodeKing** [comment]
Hi which version are you using? Have you recently upgraded from a different version?

**Comment by anthony-cole** [comment]
Hi Mike,

We are actually on version 4.09

We can't really update easily because our two programs are linked and need to still communicate after one updates, so if we updated to v5 it would no longer be able to communicate right?

Do you think this problem wouldn't occur on v5?

I'm pretty sure i found out the cause of the problem

I think one of the publishers was being shut down when it had incompletely written out a message

This would result in a listener being unable to parse the message, but putting a serializationexception catch in one of your classes has fixed the problem for me


For some reason our listener is blowing up on unhandled exceptions even though we have a handler... dunno what this is! But unrelated to xdmessaging

Anthony Cole

**Comment by TheCodeKing** [comment]
Thanks I've put in the fix for corrupt messages. 

You should be safe upgrading to version 5. Both sender and broadcaster don't have to be on the same version, so you can upgrade 1 at a time. I'd test this out before changing a prod system of course, but the message format hasn't changed in 5.

Version 5 is more of an architectural redesign to remove dynamic loading of assemblies and simplify. I also not provide a lite version which doesn't have the complexity and overhead of Network Propagation.
