### ISSUE TITLE
Crash in SimpleIocScanner with SmartAssembly

### ISSUE THREAD

**Issue by guygodin** [TheCodeKing/XDMessaging.Net#4]
I'm using RedGate's SmartAssembly to merge the various dlls of my application and XDMessaging crashes when creating the XDMessagingClient with the following exception:

 System.ArgumentException : The path is not a legal form.
 at System.IO.Path.NormalizePath(String path)
 at System.IO.Path.GetDirectoryName(string path)
 at XDMessaging.IoC.SimpleIocScanner.ScannAllAssemblies(String searchPattern)
 ...
 at XDMessaging.XDMessagingClient.ctor()

**Comment by TheCodeKing** [comment]
Should be resolved in version 5.0.0.
